language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"

    # works on Precise and Trusty
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: osx
      compiler: clang
      osx_image: xcode8

    - os: osx
      compiler: gcc
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"

  # exclude default targets (i.e. without MATRIX_EVAL environment variables)
  exclude:
    - compiler: clang
    - compiler: gcc

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - make
